blank_issues_enabled: false
contact_links:
  - name: Help translate Dropshelf
    url: https://crowdin.com/project/dropshelf
    about: Help improve translations on Crowdin.
  - name: Contact the developer
    url: https://github.com/williamckha/dropshelf-issues
    about: "Send an email to the developer: dropshelf.app@gmail.com"
